### ISSUE TITLE
Need GET /healtcheck 

### ISSUE THREAD

**Issue by dotX12** [capyfile/capyfile#10]
Could you please add the "/healtcheck" endpoint.
It is very necessary to check the functionality of the service.

**Comment by sky003** [comment]
Yeah, it's totally possible to add. I'm just not sure when I will have time for this...

**Comment by sky003** [comment]
Added in v1.2.5

So far no docs for it... but it's just [a few new flags/params](https://github.com/capyfile/capyfile/blob/bd2ad6c5dd2e5e20a091afa42030bf7751472555/capysvr/main.go#L25-L35). It can be used like this:
```
capysvr -f pipeline.yml --hc --hce /healtcheck
```
